# MyBatis-Plus配置
mybatis-plus:
  # 配置MyBatis的配置文件位置
  config-location: classpath:mybatis-config.xml
  # 配置Mapper的扫描，找到所有的Mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*.xml
  # 配置实体类的包路径，用于类型别名
  type-aliases-package: me.parade.domain.entity
  # 全局配置
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型 AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      # 字段策略 IGNORED:"忽略判断", NOT_NULL:"非 NULL 判断", NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      # 驼峰下划线转换
      table-underline: true
      # 逻辑删除配置
      # logic-delete-field: isDeleted
      # logic-delete-value: 1
      # logic-not-delete-value: 0
  # 配置类型处理器
  type-handlers-package: me.parade.framework.handler