# JWT配置
jwt:
  # JWT加密密钥,不少于 32 字节
  secret: secret_key_1234567890_abcdefg_123456_parade
  # 访问令牌过期时间（毫秒），默认30分钟
  access-token-expiration: 1800000
  # 刷新令牌过期时间（毫秒），默认7天
  refresh-token-expiration: 604800000
  # 令牌前缀
  token-prefix: "Bearer "
  # 请求头名称
  header-string: "Authorization"
  # 令牌发行者
  issuer: parade